//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class publishers
{
    public string pub_id { get; set; }
    public string pub_name { get; set; }
    public string city { get; set; }
    public string state { get; set; }
    public string country { get; set; }
}
