//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbDetalleProducto
{
    public int id { get; set; }
    public string idProducto { get; set; }
    public int idIngrediente { get; set; }
    public float cantidad { get; set; }

    public virtual tbIngredientes tbIngredientes { get; set; }
}
