//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleMovimiento
    {
        public int idDetalleMov { get; set; }
        public int idMov { get; set; }
        public int idIngrediente { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual tbIngredientes tbIngredientes { get; set; }
        public virtual tbMovimientos tbMovimientos { get; set; }
    }
}
