//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleCompras
    {
        public int idDetalle { get; set; }
        public int idCompra { get; set; }
        public int TipoCompra { get; set; }
        public string idProducto { get; set; }
        public string nombreProducto { get; set; }
        public int idMedida { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal montoTotal { get; set; }
        public decimal montoTotaDesc { get; set; }
        public decimal montoTotalImp { get; set; }
        public decimal montoTotalExo { get; set; }
        public decimal montoTotalLinea { get; set; }
    
        public virtual tbCompras tbCompras { get; set; }
        public virtual tbTipoMedidas tbTipoMedidas { get; set; }
    }
}
