//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIngredienteProveedor
    {
        public int tbIngredientes_idIngrediente { get; set; }
        public string tbProveedores_id { get; set; }
        public int tbProveedores_tipoId { get; set; }
    
        public virtual tbIngredientes tbIngredientes { get; set; }
    }
}
