//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMovimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMovimientos()
        {
            this.tbCreditos = new HashSet<tbCreditos>();
            this.tbDetalleMovimiento = new HashSet<tbDetalleMovimiento>();
            this.tbPagos = new HashSet<tbPagos>();
            this.tbCajaUsuario = new HashSet<tbCajaUsuario>();
        }
    
        public int idMovimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public int idTipoMov { get; set; }
        public bool estado { get; set; }
        public string motivo { get; set; }
        public decimal total { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCreditos> tbCreditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleMovimiento> tbDetalleMovimiento { get; set; }
        public virtual tbTipoMovimiento tbTipoMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPagos> tbPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCajaUsuario> tbCajaUsuario { get; set; }
    }
}
