//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbMonedas
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbMonedas()
    {
        this.tbCajaUsuMonedas = new HashSet<tbCajaUsuMonedas>();
    }

    public string idMoneda { get; set; }
    public string moneda { get; set; }
    public int idTipoMoneda { get; set; }
    public bool estado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbCajaUsuMonedas> tbCajaUsuMonedas { get; set; }
    public virtual tbTipoMoneda tbTipoMoneda { get; set; }
}
